# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text=b'NOMBRE', max_length=60)),
                ('apaterno', models.CharField(blank=True, help_text=b'APELLIDO PATERNO', max_length=60)),
                ('amaterno', models.CharField(blank=True, help_text=b'APELLIDO MATERNO', max_length=60)),
                ('correo', models.EmailField(help_text=b'CORREO ELECTR\xc3\x93NICO', max_length=150)),
                ('telefono', models.CharField(blank=True, help_text=b'TEL\xc3\x89FONO', max_length=60)),
            ],
        ),
    ]
